name:                "ron-hs"
version:             "0.4.0"
license:             "Apache-2.0 OR MIT"
license-file:        "LICENSE-APACHE"
author:              "morj"
maintainer:          "hackage@morj.men"

synopsis: "RON format implementation in haskell"
homepage: "https://github.com/maurges/ron-hs"
category: "Text"

ghc-options:
- -Wall -Wcompat
- -Werror=incomplete-patterns

default-extensions:
- BangPatterns
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
- TypeOperators

library:
  source-dirs: src
  dependencies:
  - "base >= 4.14.3 && < 4.21"
  - "attoparsec >= 0.14.4 && < 0.15"
  - "bytestring >= 0.10.12 && < 0.13"
  - "containers >= 0.6.5 && < 0.8"
  - "deepseq >= 1.4.4 && < 1.6"
  - "hashable >= 1.3.0 && < 1.6"
  - "scientific >= 0.3.7 && < 0.4"
  - "template-haskell >= 2.16.0 && < 2.23"
  - "text >= 1.2.4 && < 2.2"
  - "vector >= 0.12.3.1 && < 0.14"
  - "QuickCheck >= 2.14.2 && < 2.16"


tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
    - base
    - ron-hs
    - QuickCheck
    - bytestring
    - containers
    - directory
    - optics-core
    - optics-th
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
    - vector
    ghc-options:
    - -Wno-all -Wdefault
    - -Wincomplete-patterns -Werror=incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
    - base
    - ron-hs
    - base16-bytestring
    - bytestring
    - criterion
    - text
    ghc-options:
    - -Wno-all -Wdefault
    - -Wincomplete-patterns -Werror=incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
