name:                "ron-hs"
version:             "0.4.0"
license:             "Apache-2.0 OR MIT"
license-file:        "LICENSE-APACHE"
author:              "morj"
maintainer:          "hackage@morj.men"
extra-doc-files:     "changelog.txt"

synopsis: "RON format implementation in haskell"
git: "https://github.com/maurges/ron-hs"
category: "Text"
description: "RON (Rusty Object Notation) format implementation in haskell"

ghc-options:
- -Wall -Wcompat
- -Werror=incomplete-patterns

default-extensions:
- BangPatterns
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
- TypeOperators

library:
  source-dirs: src
  dependencies:
  - "base >= 4.14.3 && < 4.22"
  - "attoparsec >= 0.13.2 && < 0.15"
  - "bytestring >= 0.10.12 && < 0.13"
  - "containers >= 0.6.4 && < 0.9"
  - "deepseq >= 1.4.4 && < 1.7"
  - "hashable >= 1.3.0 && < 1.6"
  - "scientific >= 0.3.7 && < 0.4"
  - "template-haskell >= 2.16.0 && < 2.24"
  - "text >= 1.2.4 && < 2.2"
  - "vector >= 0.12.3 && < 0.14"
  - "QuickCheck >= 2.14.2 && < 2.16"


tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
    - "base >= 4.14.3 && < 4.22"
    - ron-hs
    - "QuickCheck >= 2.14.2 && < 2.16"
    - "bytestring >= 0.10.12 && < 0.13"
    - "containers >= 0.6.4 && < 0.9"
    - "directory >= 1.3.6 && < 1.4"
    - "optics-core >= 0.3 && < 0.5"
    - "optics-th >= 0.3 && < 0.5"
    - "tasty >= 1.4.2 && < 1.6"
    - "tasty-hunit >= 0.10 && < 0.11"
    - "tasty-quickcheck >= 0.10 && < 0.12"
    - "text >= 1.2.4 && < 2.2"
    - "vector >= 0.12.3 && < 0.14"
    ghc-options:
    - -Wno-all -Wdefault
    - -Wincomplete-patterns -Werror=incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
    - "base >= 4.14.3 && < 4.22"
    - ron-hs
    - "base16-bytestring >= 1.0.2 && < 1.1"
    - "bytestring >= 0.10.12 && < 0.13"
    - "criterion >= 1.5.13 && < 1.7"
    - "text >= 1.2.4 && < 2.2"
    ghc-options:
    - -Wno-all -Wdefault
    - -Wincomplete-patterns -Werror=incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
